### PR TITLE
internalize usage of Symbol

### LINKED ISSUE #25: Requires global polyfill for Symbol
http://requirebin.com/?gist=b96f3f9c9aae5a5b6edc

That means the thing doesn’t work in an ES5 environment. Even using transpiled code.

Alternative: https://www.npmjs.com/package/es6-symbol (use global when available, otherwise polyfill).

### PR DESCRIPTION
**Pull request by stoeffel**
closes #25

### CODE REVIEW

**Comment by stoeffel** [comment]
// cc @hemanth @davidchase

**Comment by davidchase** [comment]
so this is pretty nice that you internalize that Symbol usage and the polyfill will use the native `Symbol` if it exists .. this really streamlines the end user usage of this package :+1:

**Comment by stoeffel** [comment]
@tomekwi also okay for you?

**Comment by hemanth** [comment]
LGTM

**Comment by tomekwi** [comment]
Yeah, :+1: :+1:!

**Pull request merged**
